main:
  - name: Home
    url: '#'
    weight: 10
  - name: About
    url: '#about'
    weight: 20
  - name: Work with me
    url: '#work-with-me'
    weight: 30
  - name: Podcast
    url: '#podcast'
    weight: 40
  - name: Well, From Here
    url: '#well-from-here'
    weight: 50
  - name: Contact
    url: '#contact'
    weight: 60
